name: Continuous integration
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: Linux (Release)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential cmake ninja-build

      - name: Build and install using CMake
        env:
          CMAKE_GENERATOR: Ninja
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          sudo cmake --build build --target install

      - name: Run the compiled and installed binary (smoke test)
        run: |
          godotpcktool --help

      - uses: actions/upload-artifact@v2
        with:
          name: godotpcktool-linux-glibc2.31
          path: build/src/godotpcktool
